name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            echo '--- START DEPLOYMENT ---'
            cd /home/ubuntu/muslim_1
            echo '--- PULL LATEST CODE ---'
            git pull origin main
            echo '--- INSTALL DEPENDENCIES ---'
            npm install
            echo '--- START APPLICATION ---'
            # Останавливаем старый процесс (если запущен через nohup)
            pkill -f "npm run dev" || true
            nohup npm run dev > app.log 2>&1 &
            echo '--- DEPLOYMENT COMPLETED ---'