name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий на GitHub Actions
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Устанавливаем зависимости и билдим фронт
      - name: Build frontend
        run: |
          cd muslimApp
          npm install
          npm run build

      # 4. Настраиваем SSH для копирования на сервер
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 5. Копируем готовый билд на сервер
      - name: Copy frontend build to server
        run: |
          scp -r muslimApp/dist ubuntu@ec2-44-246-129-76.us-west-2.compute.amazonaws.com:/home/ubuntu/is_backend/dist