name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Проверка кода и сборка

    steps:
      # 1. Клонируем репозиторий на виртуальную машину GitHub
      - name: 🛑 Checkout кода
        uses: actions/checkout@v4

      # 2. Устанавливаем Node.js версии 18 и кэшируем зависимости npm
      - name: ⬇️ Установить Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Устанавливаем зависимости. --frozen-lockfile — чтобы не обновлять package-lock.json
      - name: 📦 Установить зависимости
        run: npm ci

      # 4. Проверяем стиль кода через ESLint
      - name: 🔍 Линтинг (проверка стиля кода)
        run: npm run lint

      # 5. Проверяем типы TypeScript. --pretty — красивый вывод
      - name: ✅ Проверка типов (TypeScript)
        run: npm run type-check


      # 6. Собираем проект. Используем тот же скрипт, что и локально: tsc -b && vite build
      - name: 🛠️ Сборка проекта
        run: npm run build

        
      # 7. (Опционально) Сохраняем результат сборки, если нужно использовать дальше
      - name: 📦 Загрузить артефакт сборки
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build
          path: dist/  # ВАЖНО: Vite по умолчанию собирает в папку dist/, не build!
