name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Посмотрим структуру репозитория (для отладки)
      - name: List repo files
        run: ls -la

      # 3. Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 4. Устанавливаем зависимости фронта
      - name: Install frontend dependencies
        working-directory: .
        run: npm ci

      # 5. Собираем фронт
      - name: Build frontend
        working-directory: .
        run: npm run build

      # 6. Архивируем dist
      - name: Archive frontend build
        run: |
          zip -r frontend_dist.zip dist

      # 7. Создаем временный файл с приватным ключом
      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PM }}" > my_key.pem
          chmod 600 my_key.pem

      # 8. Копируем архив на сервер
      - name: Upload frontend archive to server
        run: scp -o StrictHostKeyChecking=no -i my_key.pem frontend_dist.zip ubuntu@ec2-44-246-129-76.us-west-2.compute.amazonaws.com:/home/ubuntu/is_backend/

      # 9. Разархивируем фронт на сервере и удаляем архив
      - name: Extract frontend on server
        run: |
          ssh -o StrictHostKeyChecking=no -i my_key.pem ubuntu@ec2-44-246-129-76.us-west-2.compute.amazonaws.com << 'EOF'
            cd /home/ubuntu/is_backend
            unzip -o frontend_dist.zip
            rm frontend_dist.zip
          EOF


      # 11. Удаляем временный ключ
      - name: Clean up SSH key
        run: rm my_key.pem
