name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          
      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ip-172-31-30-224 << 'EOF'
            cd /home/ubuntu/muslim_1
            git pull origin main
            npm install
            nohup npm run dev > app.log 2>&1 &
          EOF
